Repository RodrigoPerezUbierna/BeDream, pull requests merged in 2022-12, with the labels that each got.

#5 [BD-30] User documentation created
  Settings/user-documentation.py
Labels: documentation

#10 Show friends and followers
  Journal/ShowFriendsAndFollowers.py
Labels: coding

#11 Release 01
  Feed/..txt
  Journal/..txt
  Journal/ShowFriendsAndFollowers.py
  Journal/createJournalEntry.py
  Profile/..txt
  Profile/createPostDB.py
  Settings/..txt
  Settings/pop-up notifications.py
  Settings/user-documentation.py
  User Management/..txt
  User Management/Login.py
  User Management/changeSkin.py
  User Management/googleAPI.py
  User Management/logout.py
  documentacion/Particiopantes del equipo.docx
  documentacion/Participantes del equipo.docx
  py/login.py
Labels: documentation, coding, release

#13 Link with device permissions
  Profile/LinkWithDevicePermissions.py
Labels: coding, integration

#14 [S02-DB32] Restrictions per post]
  Settings/..txt
  Settings/generate-restrictions-posts.py
Labels: coding, security

#16 Facebook API for Log In
  User Management/FacebookAPIforLogIn
Labels: coding, correct merge

#17 Create AllowToAddSymptomsToDailySleep.py
  Journal/AllowToAddSymptomsToDailySleep.py
Labels: enhancement, coding

#18 [S02] Generate interface profile
  Profile/interface-profile.py
Labels: design, interfaces

#20 Do FAQ and help
  Settings/DoFAQAndHelp.py
Labels: design, interfaces

#22 Release 02
  Feed/createTranslator.py
  Journal/AllowToAddSymptomsToDailySleep.py
  Profile/LinkWithDevicePermissions.py
  Profile/bibliography-links.py
  Profile/interface-profile.py
  Profile/verifiedProfile.py
  Settings/..txt
  Settings/DoFAQAndHelp.py
  Settings/generate-restrictions-posts.py
  User Management/FacebookAPIforLogIn
Labels: release

#24 [S03] Reaction menu created :)
  Feed/..txt
  Feed/reaction-menu.py
Labels: coding, design, interfaces
